/** cookies.txt format validation, WebKit↔Netscape conversion, and domain helpers. */

export type CookieSource = "webView" | "import"

export interface CookieValidationResult {
  valid: boolean
  cookieCount: number
  domains: string[]
  error?: string
}

export function validateCookiesTxt(text: string): CookieValidationResult {
  if (!text || !text.trim()) {
    return { valid: false, cookieCount: 0, domains: [], error: "内容为空。" }
  }

  const lines = text.split(/\r?\n/)
  const domains = new Set<string>()
  let cookieCount = 0
  let hasValidLine = false

  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i].trim()
    if (!line || line.startsWith("#")) continue
    hasValidLine = true

    // Netscape cookies.txt 格式：7 个 tab 分隔的字段
    const fields = line.split("\t")
    if (fields.length < 7) {
      return {
        valid: false,
        cookieCount: 0,
        domains: [],
        error: `第 ${i + 1} 行格式无效：需要 7 个 tab 分隔的字段（domain, include_subdomains, path, secure, expiration, name, value）。`,
      }
    }

    const [domain, , , secure, expiration, name] = fields
    if (!domain || !name) {
      return {
        valid: false,
        cookieCount: 0,
        domains: [],
        error: `第 ${i + 1} 行缺少 domain 或 name 字段。`,
      }
    }

    if (secure !== "TRUE" && secure !== "FALSE") {
      return {
        valid: false,
        cookieCount: 0,
        domains: [],
        error: `第 ${i + 1} 行 secure 字段必须为 TRUE 或 FALSE。`,
      }
    }

    const exp = Number(expiration)
    if (!Number.isFinite(exp) || exp < 0) {
      return {
        valid: false,
        cookieCount: 0,
        domains: [],
        error: `第 ${i + 1} 行 expiration 字段无效（应为非负整数秒数）。`,
      }
    }

    domains.add(domain.replace(/^\./, ""))
    cookieCount += 1
  }

  if (!hasValidLine) {
    return { valid: false, cookieCount: 0, domains: [], error: "没有找到 Cookie 条目（所有行都是注释或空行）。" }
  }

  return { valid: true, cookieCount, domains: [...domains] }
}

/**
 * 将 WebKit Cookie 列表转换为 Netscape cookies.txt 格式文本。
 * Cookie 接口来自 WebViewController.getAllCookies() 的返回值。
 */
export function webkitCookiesToNetscape(cookies: {
  name: string
  value: string
  domain: string
  path: string
  isSecure: boolean
  isHTTPOnly?: boolean
  isSessionOnly?: boolean
  expiresDate?: Date | null
}[]): string {
  const lines: string[] = [
    "# Netscape HTTP Cookie File",
    "# Generated by Universal Video Downloader",
    "",
  ]

  for (const cookie of cookies) {
    if (!cookie.name || !cookie.domain) continue
    const domain = cookie.domain
    const includeSubdomains = "TRUE"
    const path = cookie.path || "/"
    const secure = cookie.isSecure ? "TRUE" : "FALSE"
    let expires = 0
    if (cookie.expiresDate instanceof Date && cookie.expiresDate.getTime() > 0) {
      expires = Math.floor(cookie.expiresDate.getTime() / 1000)
    }
    lines.push([
      domain,
      includeSubdomains,
      path,
      secure,
      String(expires),
      cookie.name,
      cookie.value ?? "",
    ].join("\t"))
  }

  return lines.join("\n")
}

export function inferDomainFromUrl(url: string): string {
  try {
    const parsed = new URL(url)
    return parsed.hostname || "未知域名"
  } catch {
    return "未知域名"
  }
}

export function inferDomainFromCookiesText(text: string): string {
  const validation = validateCookiesTxt(text)
  return validation.domains[0] || "未知域名"
}

/** 从 hostname 提取根域名（如 www.youtube.com → youtube.com） */
export function extractRootDomain(hostname: string): string {
  let host = hostname.replace(/^\.+/, "").toLowerCase()
  const multiLevelTlds = [
    ".co.uk", ".co.jp", ".com.cn", ".com.au", ".co.kr", ".com.br",
    ".com.tw", ".com.hk", ".co.nz", ".org.uk", ".ac.uk", ".gov.uk",
  ]
  for (const tld of multiLevelTlds) {
    if (host.endsWith(tld)) {
      const parts = host.split(".")
      if (parts.length >= 3) return parts.slice(-3).join(".")
    }
  }
  const parts = host.split(".")
  if (parts.length >= 2) return parts.slice(-2).join(".")
  return host
}

/** 从 Cookie 列表中筛选属于指定域名（含子域）的 Cookie */
export function filterCookiesByDomain<T extends { domain: string }>(
  cookies: T[],
  targetDomain: string,
): T[] {
  const normalized = targetDomain.replace(/^\./, "").toLowerCase()
  return cookies.filter(cookie => {
    const cookieDomain = (cookie.domain || "").replace(/^\./, "").toLowerCase()
    return cookieDomain === normalized || cookieDomain.endsWith("." + normalized)
  })
}
